
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secret
  namespace: <desired-namespace>
type: Opaque
data:
  PULUMI_AGENT_TOKEN: <api token>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/name: pulumi-workflow-agent-pool
  name: workflow-agent-pool
  namespace: <desired-namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulumi-workflow-agent-pool
  template:
    metadata:
      labels:
        app: pulumi-workflow-agent-pool
        app.kubernetes.io/name: pulumi-workflow-agent-pool
    spec:
      containers:
      - name: agent
        image: <image_location>
        imagePullPolicy: Always
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: PULUMI_AGENT_SHARED_VOLUME_DIRECTORY
          value: /mnt/work
        - name: PULUMI_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              key: PULUMI_AGENT_TOKEN
              name: agent-secret
        volumeMounts:
        - mountPath: /mnt/work
          name: agent-work
      - name: dind
        image: docker:dind
        imagePullPolicy: Always
        command:
        - dockerd
        - --host
        - tcp://127.0.0.1:2375
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/work
          name: agent-work
      volumes:
      - emptyDir: {}
        name: agent-work
