apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-managed-deployment-agent.fullname" . }}-config
  labels:
  {{- include "customer-managed-deployment-agent.labels" . | nindent 4 }}
data:
  PULUMI_AGENT_IMAGE: {{ include "customer-managed-deployment-agent.imageName" . | quote }}
  PULUMI_AGENT_IMAGE_PULL_POLICY: {{ .Values.image.pullPolicy | quote }}
  PULUMI_AGENT_SERVICE_URL: {{ .Values.customerManagedAgentConfig.backEndApiUrl | quote }}
  