apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customer-managed-deployment-agent.fullname" . }}-deployment-agent
  labels:
  {{- include "customer-managed-deployment-agent.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
