apiVersion: v1
data:
  PULUMI_AGENT_IMAGE: "pulumi/customer-managed-workflow-agent:latest-arm64"
  PULUMI_AGENT_IMAGE_PULL_POLICY: "IfNotPresent"
  PULUMI_AGENT_SERVICE_URL: "https://api.pulumi.com"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: customer-managed-workflow-agent
  name: agent-config
  namespace: cmda

---

apiVersion: v1
data:
  PULUMI_AGENT_TOKEN: <agent token>
kind: Secret
metadata:
  name: agent-secret
  namespace: cmda

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: customer-managed-workflow-agent
  name: workflow-agent
  namespace: cmda

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: customer-managed-workflow-agent
  name: workflow-agent
  namespace: cmda
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: customer-managed-workflow-agent
  name: workflow-agent
  namespace: cmda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-agent
subjects:
  - kind: ServiceAccount
    name: workflow-agent

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/name: pulumi-workflow-agent-pool
  labels:
    app.kubernetes.io/name: customer-managed-workflow-agent
  name: workflow-agent-pool
  namespace: cmda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-managed-workflow-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-managed-workflow-agent
    spec:
      containers:
        - env:
            - name: PULUMI_AGENT_DEPLOY_TARGET
              value: kubernetes
            - name: PULUMI_AGENT_SHARED_VOLUME_DIRECTORY
              value: /mnt/work
            - name: PULUMI_AGENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: PULUMI_AGENT_SERVICE_URL
                  name: agent-config
            - name: PULUMI_AGENT_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: PULUMI_AGENT_IMAGE
                  name: agent-config
            - name: PULUMI_AGENT_IMAGE_PULL_POLICY
              valueFrom:
                configMapKeyRef:
                  key: PULUMI_AGENT_IMAGE_PULL_POLICY
                  name: agent-config
            - name: PULUMI_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: PULUMI_AGENT_TOKEN
                  name: agent-secret
          image: pulumi/customer-managed-workflow-agent:latest-arm64
          imagePullPolicy: IfNotPresent
          name: agent
          volumeMounts:
            - mountPath: /mnt/work
              name: agent-work
      serviceAccountName: workflow-agent
      volumes:
        - emptyDir: {}
          name: agent-work
        - configMap:
            name: agent-config
          name: agent-config
