permissions: write-all # Equivalent to default permissions plus id-token: write
name: Publish Prerelease

on:
  push:
    tags:
      - v*.*.*-**

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-customer-managed-workflow-agent
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN,COSIGN_PASSWORD

jobs:
  publish:
    uses: ./.github/workflows/stage-publish.yaml
    with:
      goreleaser-args: -p 10 -f .goreleaser.prerelease.yaml --clean --skip=validate --timeout 60m0s --release-notes=CHANGELOG_PENDING.md
    secrets: inherit
