permissions: write-all # Equivalent to default permissions plus id-token: write
name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string

env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-customer-managed-workflow-agent
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: GITHUB_TOKEN=PULUMI_BOT_TOKEN,COSIGN_PASSWORD

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          token: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'
      - name: Check Cosign install
        run: cosign version
      - name: Set BUILD_STAMP
        run: |
          echo "BUILD_STAMP=$(cd ./pulumi-service && date -u '+%Y-%m-%d_%I:%M:%S%p')" >> $GITHUB_ENV
      - name: Set BUILD_GIT_HASH
        run: |
          echo "BUILD_GIT_HASH=$(cd ./pulumi-service && git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Login to Docker Hub as pulumi-bot
        uses: docker/login-action@v3
        with:
          username: ${{ steps.esc-secrets.outputs.DOCKER_HUB_USERNAME }}
          password: ${{ steps.esc-secrets.outputs.DOCKER_HUB_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: ${{ inputs.goreleaser-args }}
          version: '~> v2'
        env:
          REPO_OWNER: pulumi
